In [14]:
import numpy as np

a = np.arange(3)
b = np.arange(3)
m = np.arange(4).reshape((2, 2))
print(m)
print(m.T)

print(m * m)
print(m @ m)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]


In [29]:
desired_customers = 8000
desired_rev = 10_000_000
cvr = 0.02
gmv_per_customer = 289
weekly_rewards_value = 150_000
weeks_left = 13 # todo: make dynamic

signups_needed = desired_customers / cvr
signups_per_week_needed = signups_needed / weeks_left
signups_per_day_needed = signups_per_week_needed / 7
est_gmv = signups_per_week_needed*gmv_per_customer

customers_per_week_needed = desired_customers / weeks_left
customers_needed_for_secondary = weekly_rewards_value / gmv_per_customer
primary_gmv_pct = (customers_per_week_needed - customers_needed_for_secondary) / customers_per_week_needed
primary_gmv = round(primary_gmv_pct * est_gmv)
secondary_gmv = round((1 - primary_gmv_pct) * est_gmv * 0.05)

breakeven_marketing_budget = primary_gmv + secondary_gmv
breakeven_cpa = breakeven_marketing_budget / signups_needed

In [ ]:


for i in range(weeks_left*7):
    

