In [14]:
import numpy as np

a = np.arange(3)
b = np.arange(3)
m = np.arange(4).reshape((2, 2))
print(m)
print(m.T)

print(m * m)
print(m @ m)

[[0 1]
 [2 3]]
[[0 2]
 [1 3]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]
